kind: Secret
apiVersion: v1
metadata:
  name: avp-secret
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  VAULT_TOKEN: ${VAULT_TOKEN}

